---
name: Build

on:
  workflow_call:
    inputs:
      tag_latest:
        type: boolean
        default: false

env:
  DOCKER_REGISTRY: ghcr.io/lucasl0st/ipv4-for-ipv6_only-http-proxy

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build and push
        run: |
          make docker push=true tag-latest=${{ inputs.tag_latest }}
