---
name: Push to main
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.create_tag.outputs.new_tag }}
      changelog: ${{ steps.create_tag.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.2
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/_build.yaml
    needs: tag
    with:
      tag_latest: true
      additional_tag: ${{ needs.tag.outputs.tag }}

  release:
    runs-on: ubuntu-22.04
    needs:
      - tag
      - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ needs.build.outputs.binary_artifact }}

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.tag }}
          name: ${{ needs.tag.outputs.tag }}
          body: ${{ needs.tag.outputs.changelog }}
          artifacts: ${{ needs.build.outputs.binary_artifact }}/*
